events {
    use epoll;
    worker_connections 128;
}

http {
    upstream stocks1_rev {
        server stocks1-a:8000 weight=3;
        server stocks1-b:8000 weight=1;
    }

    upstream stocks2_rev {
        server stocks2:8000;
    }

    server {
        listen 80;

        # Forward requests to /stocks1 to the load-balanced stocks1 service
        location /stocks1 {
            proxy_pass http://stocks1_rev/stocks;
            limit_except GET {
                # Allow only GET requests, deny others
                deny all;
            }
        }

        # Forward requests to /stocks2 to the stocks2 service
        location /stocks2 {
            proxy_pass http://stocks2_rev/stocks;
            limit_except GET {
                # Allow only GET requests, deny others
                deny all;
            }
        }

        error_log /var/log/nginx/error.log debug;
    }
}